import localizationKeys from "./localization-keys";

const ar = {
  // auth
  [localizationKeys.LOGIN]: "تسجيل الدخول",
  [localizationKeys.Hithere]: "مرحبًا!",
  [localizationKeys.Logintomanageyourtranslatorslistsandfilterthe]:
    "سجّل الدخول لإدارة قوائم المترجمين وتصفية",
  [localizationKeys.resultstosuityourdesiredjobtype]:
    "النتائج التي تناسب نوع الوظيفة التي تريدها",
  [localizationKeys.FORGOTPASSWORD]: "نسيت كلمة المرور",
  [localizationKeys.RememberMe]: "تذكرني",
  [localizationKeys.OR]: "أو",
  [localizationKeys.CREATENEWACCOUNT]: "إنشاء حساب جديد",
  [localizationKeys.sentverification]: "التحقق المرسل",
  [localizationKeys.Email]: "البريد الإلكتروني",
  [localizationKeys.Password]: "كلمة المرور",
  [localizationKeys.NEWAccount]: "حساب جديد",
  [localizationKeys.FULLNAME]: "الاسم الكامل",
  [localizationKeys.PHONE]: "الهاتف",
  [localizationKeys.IAGREETOTHETERMSANDCONDITIONS]: "أوافق على الشروط والأحكام",
  [localizationKeys.SIGNUP]: "انشاء الحساب",
  [localizationKeys.GOTOLOGIN]: "الانتقال إلى تسجيل الدخول",
  [localizationKeys.RESETPASSWORD]: "تغير كلمه المرور",
  [localizationKeys.NewPassword]: "كلمة المرور الجديدة",
  [localizationKeys.ReEnterPassword]: "عادة إدخال كلمة المرور",
  // home
  [localizationKeys.SELL]: "بيع",
  [localizationKeys.Welcome]: "مرحبًا",
  [localizationKeys.English]: "الانجليزية",
  [localizationKeys.Arabic]: "العربية",
  [localizationKeys.AllCategories]: "جميع الفئات",
  [localizationKeys.TRY]: "جرب",
  [localizationKeys.Buysellandfindjustaboutanythingusingtheapponyourmobile]:
    "الشراء والبيع والعثور على أي شيء باستخدام التطبيق على هاتفك المحمول",
  [localizationKeys.ChooseType]: "اختر النوع",
  [localizationKeys.Choosemake]: "اختر الماركة",
  [localizationKeys.ChooseModel]: "اختر الموديل",
  [localizationKeys.Chooseyear]: "اختر السنة",
  [localizationKeys.SEARCHNOW]: "ابحث الآن",
  [localizationKeys.Type]: "النوع",
  [localizationKeys.make]: "الماركة",
  [localizationKeys.Model]: "الموديل",
  [localizationKeys.year]: "السنة",
  [localizationKeys.Keyword]: "الكلمات الدالة...",
  [localizationKeys.NewUsed]: "الجديدة والمستعملة",
  [localizationKeys.New]: "جديد",
  [localizationKeys.Used]: "مستعملة",
  [localizationKeys.Location]: "الموقع",
  [localizationKeys.Findamazingdealsonthego]:
    "اعثر على صفقات مذهلة أثناء التنقل.",
  [localizationKeys.Downloadtheappnow]: "قم بتنزيل التطبيق الآن!",
  [localizationKeys.Freshrecommendations]: "توصيات جديدة",
  [localizationKeys.Anewexperienceintheworldofsecondhandpurchase]:
    "تجربة جديدة في عالم شراء الأشياء المستعملة",
  [localizationKeys.TAKEALOOK]: "خذ نظرة!",
  [localizationKeys.Bikesforsale]: "دراجات للبيع",
  [localizationKeys.NewsReviews]: "أخبار ومراجعات",
  [localizationKeys.GeneralHelp]: "تعليمات عامة",
  [localizationKeys.OurApp]: "عن التطبيق",
  // profile
  [localizationKeys.TotalPageView]: "إجمالي عرض الصفحة",
  [localizationKeys.logout]: "تسجيل الخروج",
  [localizationKeys.MyAccout]: "حسابي",
  [localizationKeys.REJECTED]: "مرفوض",
  [localizationKeys.PENDING]: "معلق",
  [localizationKeys.PUBLISHED]: "تم النشر",
  [localizationKeys.DRAFTED]: "صياغة",
  [localizationKeys.EXPIRED]: "منتهية الصلاحية",
  // add ads
  [localizationKeys.Nowchoosetherightcategory]: "الآن اختر الفئة الصحيحة",
  [localizationKeys.foryourad]: "لإعلانك:",
  [localizationKeys.ConsultantPsychiatristExperienceInAdultPsychiatry]:
    "طبيب نفسي استشاري - خبرة في الطب النفسي للبالغين",
  [localizationKeys.AndAddictionMedicineITreatMany]:
    "وطب الإدمان أتعامل مع الكثيرين",
  [localizationKeys.next]: "التالي",
  [localizationKeys.Category]: "الفئة",
  [localizationKeys.SubCategory]: "الفئة الفرعية",
  [localizationKeys.Yourealmostthere]: "أنت هناك تقريبًا!",
  [localizationKeys.Includeasmuchdetailsandpicturesaspossible]:
    "قم بتضمين أكبر قدر ممكن من التفاصيل والصور",
  [localizationKeys.andsettherightprice]: "وتعيين السعر الصحيح!",
  [localizationKeys.UPLOAD]: "تحميل",
  [localizationKeys.YOURPHOTO]: "صورك الخاصة للاعلان",
  [localizationKeys.POST]: "انشر الاعلان",
  [localizationKeys.title]: "العنوان",
  [localizationKeys.price]: "السعر",
  [localizationKeys.DESCRIPTIONYOURAD]: "وصف إعلانك ...",
  [localizationKeys.description]: "الوصف",
  [localizationKeys.brand]: "العلامة التجارية",
  [localizationKeys.model]: "الموديل",
  [localizationKeys.AddBrand]: "إضافة العلامة التجارية",
  [localizationKeys.AddModel]: "إضافة الموديل",
  [localizationKeys.city]: "المدينة",
  [localizationKeys.usage]: "الاستخدام",
  [localizationKeys.ITEMOVERVIEW]: "نظرة عامة على العنصر",
  [localizationKeys.YOUMAYALSOLIKE]: "ربما تعجبك جدًا",
  [localizationKeys.MOREOPTIONYOULIKE]: "المزيد من الخيارات التي تحبها",
  //
  [localizationKeys.BACKTOCATEGORY]: "عودة إلى الفئة",
  [localizationKeys.ABOUTTHISDEALER]: "حول هذا البائع",
  [localizationKeys.CALLNOW]: "اتصل الان",
  [localizationKeys.Emailcopysuccess]: "نجاح نسخ البريد الإلكتروني",
  [localizationKeys.ASKTHEDEALERAQUESTION]: "اسأل البائع عن سؤال",
  [localizationKeys.IMINTERESTEDPLEASECONTACTME]: "نا مهتم ، يرجى الاتصال بي؟",
  [localizationKeys.CONTACTMEABOUTINSURANCE]: "اتصل بي بخصوص التأمين",
  [localizationKeys.CONFIRMDEALERRESPONSE]: " تأكيد استجابة البائع",
  [localizationKeys.FILLINTHISFORMFORMENEXTTIME]:
    "املأ هذا النموذج لي في المرة القادمة",
  [localizationKeys.SENDENQUIRY]: "أرسل إستفسار",
  //
  [localizationKeys.Bikesforsale]: "دراجات للبيع",
  [localizationKeys.NewsReviews]: "خبار ومراجعات",
  [localizationKeys.GeneralHelp]: "تعليمات عامة",
  [localizationKeys.OurApp]: "تطبيقنا",

  [localizationKeys.Usedbikesforsale]: "دراجات مستعملة للبيع",
  [localizationKeys.Newbikesforsale]: "دراجات جديدة للبيع",
  [localizationKeys.BikeFactsHistoryReports]: "تقارير سجل حقائق الدراجة",
  [localizationKeys.BikeNews]: "أخبار الدراجة",
  [localizationKeys.BikeReviews]: "مراجعات الدراجة",
  [localizationKeys.BikeAdvice]: "نصيحة الدراجة",
  [localizationKeys.BikeVideos]: "مقاطع فيديو الدراجة",
  [localizationKeys.TermsConditions]: "الشروط والأحكام",
  [localizationKeys.Privacy]: "الخصوصية",
  [localizationKeys.ContactUs]: "اتصل بنا",
  [localizationKeys.AboutUs]: "نبذة عنا",
  [localizationKeys.DownloadOurAppNow]: "قم بتنزيل تطبيقنا الآن",
  [localizationKeys.OnAppStoreGooglePlay]: "على App Store / Google Play",
  //
  [localizationKeys.TALKTOUS]: "تحدث إلينا",
  [localizationKeys.CONTACT]: "اتصل",
  [localizationKeys.US]: "بنا",
  [localizationKeys.TAKEACOFFEEWITHUS]: "تناول القهوة معنا",
  [localizationKeys.CONTACTUS]: "اتصل بنا",
  [localizationKeys.DOYOU]: "هل أنت",
  [localizationKeys.HAVEANY]: "لديك أي",
  [localizationKeys.QUESTIONS]: "أسئلة",
  [localizationKeys.firstName]: "الاسم الأول",
  [localizationKeys.familyName]: "اسم العائلة",
  [localizationKeys.subject]: "الموضوع",
  [localizationKeys.MESSAGE]: "رسالة",
  [localizationKeys.SEND]: "إرسال",
  [localizationKeys.ForBuyers]: "للمشترين",
  [localizationKeys.ByBuyers]: "بواسطة المشترين",
  [localizationKeys.itisalongestablishedfactthatareaderwillbe]:
    "هناك حقيقة مثبتة منذ زمن طويل وهي أن القارئ سيكون كذلك",
  [localizationKeys.distractedbythereadablecontent]: "يصرف المحتوى المقروء",
  [localizationKeys.ofapagewhenlookingatitslayoutthepointofusing]:
    "من الصفحة عند النظر إلى تخطيطها. نقطة الاستخدام",
  [localizationKeys.loremipsumisthatithasa]: "هو أنه يحتوي على",
  //
  [localizationKeys.OURSTORY]: "قصتنا",
  [localizationKeys.ABOUTUS]: "معلومات عنا",

  [localizationKeys.buy]: "اشتري الان",
  [localizationKeys.LEARNMORE]: "اطلع علي المزيد",
  [localizationKeys.SUBMIT]: "عرض من",
  //
  [localizationKeys.ALLMANUFACTURES]: "جميع المصانع",
  [localizationKeys.SearchRuslt]: "نتيجة البحث",
  [localizationKeys.TRANSMISSIONTYPEF]: "نوع الإرسال",
  [localizationKeys.PRICE]: "سعر",
};

export default ar;
