const localizationKeys = {
  // auth
  LOGIN: "LOGIN",
  Hithere: "Hithere!",
  Logintomanageyourtranslatorslistsandfilterthe:
    "Logintomanageyourtranslatorslistsandfilterthe",
  resultstosuityourdesiredjobtype: "resultstosuityourdesiredjobtype",
  FORGOTPASSWORD: "FORGOTPASSWORD ",
  RememberMe: "RememberMe",
  OR: "OR",
  CREATENEWACCOUNT: "CREATENEWACCOUNT",
  sentverification: "sentverification",
  Email: "Email",
  Password: "Password",
  NEWAccount: "NEWAccount",
  FULLNAME: "FULLNAME",
  PHONE: "PHONE",
  PASSWORD: "PASSWORD",
  IAGREETOTHETERMSANDCONDITIONS: "IAGREETOTHETERMSANDCONDITIONS",
  SIGNUP: "SIGNUP",
  GOTOLOGIN: "GOTOLOGIN",
  // home
  SELL: "SELL",
  Welcome: "Welcome",
  English: "English",
  Arabic: "Arabic",
  AllCategories: "AllCategories",
  TRY: "TRY",
  Buysellandfindjustaboutanythingusingtheapponyourmobile:
    "Buysellandfindjustaboutanythingusingtheapponyourmobile",
  ChooseType: "ChooseType",
  Choosemake: "Choosemake",
  ChooseModel: "ChooseModel",
  Chooseyear: "Chooseyear",
  SEARCHNOW: "SEARCHNOW",
  Type: "Type",
  make: "make",
  Model: "Model",
  year: "year",
  Keyword: "Keyword",
  Location: "Location",
  NewUsed: "NewUsed",
  New: "New",
  Used: "Used",
  Findamazingdealsonthego: "Findamazingdealsonthego",
  Downloadtheappnow: "Downloadtheappnow",
  Freshrecommendations: "Freshrecommendations",
  Anewexperienceintheworldofsecondhandpurchase:
    "Anewexperienceintheworldofsecondhandpurchase",
  Bikesforsale: "Bikesforsale",
  NewsReviews: "NewsReviews",
  GeneralHelp: "GeneralHelp",
  OurApp: "OurApp",
  TAKEALOOK: "TAKEALOOK",
  // profile
  TotalPageView: "TotalPageView",
  logout: "logout",
  MyAccout: "MyAccount",
  REJECTED: "REJECTED",
  PENDING: "PENDING",
  PUBLISHED: "PUBLISHED",
  DRAFTED: "DRAFTED",
  EXPIRED: "EXPIRED",
  // add ads
  Nowchoosetherightcategory: "Nowchoosetherightcategory",
  foryourad: "foryourad",
  ConsultantPsychiatristExperienceInAdultPsychiatry:
    "ConsultantPsychiatristExperienceInAdultPsychiatry",
  AndAddictionMedicineITreatMany: "AndAddictionMedicineITreatMany",
  next: "next",
  Category: "Category",
  SubCategory: "SubCategory",
  Yourealmostthere: "Yourealmostthere",
  Includeasmuchdetailsandpicturesaspossible:
    "Includeasmuchdetailsandpicturesaspossible",
  andsettherightprice: "andsettherightprice",
  UPLOAD: "UPLOAD",
  YOURPHOTO: "YOURPHOTO",
  title: "title",
  price: "price",
  DESCRIPTIONYOURAD: "DESCRIPTIONYOURAD",
  AddBrand: "AddBrand",
  AddModel: "AddModel",
  city: "city",
  usage: "usage",
};

export default localizationKeys;
