const localizationKeys = {
  // auth
  LOGIN: "LOGIN",
  Hithere: "Hithere!",
  Logintomanageyourtranslatorslistsandfilterthe:
    "Logintomanageyourtranslatorslistsandfilterthe",
  resultstosuityourdesiredjobtype: "resultstosuityourdesiredjobtype",
  FORGOTPASSWORD: "FORGOTPASSWORD ",
  RememberMe: "RememberMe",
  OR: "OR",
  CREATENEWACCOUNT: "CREATENEWACCOUNT",
  sentverification: "sentverification",
  Email: "Email",
  Password: "Password",
  NEWAccount: "NEWAccount",
  FULLNAME: "FULLNAME",
  PHONE: "PHONE",
  PASSWORD: "PASSWORD",
  IAGREETOTHETERMSANDCONDITIONS: "IAGREETOTHETERMSANDCONDITIONS",
  SIGNUP: "SIGNUP",
  GOTOLOGIN: "GOTOLOGIN",
  RESETPASSWORD: " RESETPASSWORD",
  NewPassword: "NewPassword",
  ReEnterPassword: "ReEnterPassword",
  // home
  SELL: "SELL",
  Welcome: "Welcome",
  English: "English",
  Arabic: "Arabic",
  AllCategories: "AllCategories",
  TRY: "TRY",
  Buysellandfindjustaboutanythingusingtheapponyourmobile:
    "Buysellandfindjustaboutanythingusingtheapponyourmobile",
  ChooseType: "ChooseType",
  Choosemake: "Choosemake",
  ChooseModel: "ChooseModel",
  Chooseyear: "Chooseyear",
  SEARCHNOW: "SEARCHNOW",
  Type: "Type",
  make: "make",
  Model: "Model",
  year: "year",
  Keyword: "Keyword",
  Location: "Location",
  NewUsed: "NewUsed",
  New: "New",
  Used: "Used",
  Findamazingdealsonthego: "Findamazingdealsonthego",
  Downloadtheappnow: "Downloadtheappnow",
  Freshrecommendations: "Freshrecommendations",
  Anewexperienceintheworldofsecondhandpurchase:
    "Anewexperienceintheworldofsecondhandpurchase",
  Bikesforsale: "Bikesforsale",
  NewsReviews: "NewsReviews",
  GeneralHelp: "GeneralHelp",
  OurApp: "OurApp",
  TAKEALOOK: "TAKEALOOK",
  // profile
  TotalPageView: "TotalPageView",
  logout: "logout",
  MyAccout: "MyAccount",
  REJECTED: "REJECTED",
  PENDING: "PENDING",
  PUBLISHED: "PUBLISHED",
  DRAFTED: "DRAFTED",
  EXPIRED: "EXPIRED",
  // add ads
  Nowchoosetherightcategory: "Nowchoosetherightcategory",
  foryourad: "foryourad",
  ConsultantPsychiatristExperienceInAdultPsychiatry:
    "ConsultantPsychiatristExperienceInAdultPsychiatry",
  AndAddictionMedicineITreatMany: "AndAddictionMedicineITreatMany",
  next: "next",
  Category: "Category",
  SubCategory: "SubCategory",
  Yourealmostthere: "Yourealmostthere",
  Includeasmuchdetailsandpicturesaspossible:
    "Includeasmuchdetailsandpicturesaspossible",
  andsettherightprice: "andsettherightprice",
  UPLOAD: "UPLOAD",
  YOURPHOTO: "YOURPHOTO",
  POST: "POST",
  title: "title",
  price: "price",
  DESCRIPTIONYOURAD: "DESCRIPTIONYOURAD",
  description: "description",
  AddBrand: "AddBrand",
  brand: "brand",
  model: "model",
  AddModel: "AddModel",
  city: "city",
  usage: "usage",
  ITEMOVERVIEW: "ITEMOVERVIEW",
  YOUMAYALSOLIKE: "YOUMAYALSOLIKE",
  MOREOPTIONYOULIKE: "MOREOPTIONYOULIKE",

  BACKTOCATEGORY: "BACKTOCATEGORY",
  ABOUTTHISDEALER: "ABOUTTHISDEALER",
  CALLNOW: "CALLNOW",
  Emailcopysuccess: "Emailcopysuccess",
  ASKTHEDEALERAQUESTION: "ASKTHEDEALERAQUESTION",
  IMINTERESTEDPLEASECONTACTME: "IMINTERESTEDPLEASECONTACTME",
  CONTACTMEABOUTINSURANCE: "CONTACTMEABOUTINSURANCE",
  CONFIRMDEALERRESPONSE: "CONFIRMDEALERRESPONSE",
  FILLINTHISFORMFORMENEXTTIME: "FILLINTHISFORMFORMENEXTTIME",
  SENDENQUIRY: " SENDENQUIRY",

  Usedbikesforsale: "Usedbikesforsale",
  Newbikesforsale: "Newbikesforsale",
  BikeFactsHistoryReports: "BikeFactsHistoryReports",
  BikeNews: "BikeNews",
  BikeReviews: "BikeReviews",
  BikeAdvice: "BikeAdvice",
  BikeVideos: "BikeVideos",
  TermsConditions: "TermsConditions",
  Privacy: "Privacy",
  ContactUs: "ContactUs",
  AboutUs: "AboutsUs",
  DownloadOurAppNow: "DownloadOurAppNow",
  OnAppStoreGooglePlay: "OnAppStoreGooglePlay",
  //
  TALKTOUS: "TALKTOUS",
  CONTACT: "CONTACT",
  US: "US",
  TAKEACOFFEEWITHUS: "TAKEACOFFEEWITHUS",
  CONTACTUS: "CONTACTUS",
  DOYOU: "DOYOU",
  HAVEANY: "HAVEANY",
  QUESTIONS: "QUESTIONS",
  firstName: "firstName",
  familyName: "familyName",
  subject: "subject",
  MESSAGE: "MESSAGE",
  SEND: "SEND",
  ForBuyers: "ForBuyers",
  ByBuyers: "ByBuyers",
  itisalongestablishedfactthatareaderwillbe:
    "itisalongestablishedfactthatareaderwillbe",
  distractedbythereadablecontent: "distractedbythereadablecontent",
  ofapagewhenlookingatitslayoutthepointofusing:
    "ofapagewhenlookingatitslayoutthepointofusing",
  loremipsumisthatithasa: "loremipsumisthatithasa",
  //
  OURSTORY: "OURSTORY",
  ABOUTUS: "ABOUTUS",
  //
  buy: "buy",
  LEARNMORE: " LEARNMORE",
  SUBMIT: "SUBMIT",
  ALLMANUFACTURES: "ALLMANUFACTURES",
  SearchRuslt: "SearchRuslt",
  TRANSMISSIONTYPEF: "TRANSMISSIONTYPEF",
  PRICE: "PRICE",
};

export default localizationKeys;
